### ISSUE TITLE
Spring Cloud Stream App Starter build enhancements

### ISSUE THREAD

**Issue by sobychacko** [spring-io/build-scripts#12]
Possible common jar. (https://github.com/spring-io/build-scripts/issues/2)
Dockerization of components. 

Here are the common components that the scst app starter Jenkins build uses:

```io.springframework.common.Cron
 io.springframework.common.JdkConfig
 io.springframework.common.Maven
 io.springframework.common.TestPublisher 
 javaposse.jobdsl.dsl.DslFactory
  io.springframework.common.Artifactory.artifactoryMaven3Configurator
 io.springframework.common.Artifactory.artifactoryMavenBuild

io.springframework.common.BuildAndDeploy
io.springframework.cloud.view.DashboardViewBuilder```

**Comment by sabbyanandan** [comment]
As a user, I'd like to use the build machinery to build, test, and upload Spring Cloud Stream App Starters and Spring Cloud Task App Starters as part of the dockerized Jenkins CI plan. 

**Acceptance:**
- Common/Cloud dependencies are separated from stream/task build machinery 
- A `docker-compose.yml` defines and sets up the relevant components to bootstrap build infrastructure

**Comment by sobychacko** [comment]
We need this seed job in the docker image for jenkins:
https://jenkins.spring.io/view/Seeds/job/scst-app-starters-seed/
and we don't need spring-cloud-stream seed.

@sabby - can you confirm if we need to keep the task app starters seed there in the image?

**Comment by marcingrzejszczak** [comment]
I've updated the code with your suggestions. Now you can call

`./gradlew initializeAndStartScst -PrepoUrl=http://foo/bar`

That way the seed job for `scst-app-starters-seed` will be added and its repo URL will be changed to whatever you pass as a `repoUrl` property. That means that if someone forks our code one will be able to point to that forked repo.

**Comment by marcingrzejszczak** [comment]
Can we close this?

**Comment by sobychacko** [comment]
sure. closing it now.
