### ISSUE TITLE
Start publishing common as a jar

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-io/build-scripts#2]

**Comment by marcingrzejszczak** [comment]
Let's revive this. Where will we store the common code? We need to decide on some repo somewhere. Any ideas @spencergibb @sobychacko ?

**Comment by sobychacko** [comment]
@marcingrzejszczak I think the common code should move to a new repo. Then we can publish the corresponding artifacts from the CI build for that repo. With the changes in https://github.com/spring-io/build-scripts/pull/21 are we moving the build-scripts out of spring-io?

**Comment by marcingrzejszczak** [comment]
Yeah - that's the process. Let's first rename stuff properly and then move out. We need a place to move out first ;) Which org and what should be the name of the repo?

**Comment by sobychacko** [comment]
Not sure what will be the right org since its used across multiple projects. do we have any org for operational/devops kind of repos?

**Comment by marcingrzejszczak** [comment]
@trevormarshall ^^

**Comment by trevormarshall** [comment]
We don't keep an org specific to infra. spring-projects is the most generic org and I keep my configuration repos there. or here.

**Comment by trevormarshall** [comment]
per @marcingrzejszczak created https://github.com/spring-projects/jenkins-common

**Comment by marcingrzejszczak** [comment]
Done - code is in https://github.com/spring-projects/jenkins-common together with a readme file how to configure stuff. It's enough for you to apply this gradle script https://github.com/spring-io/build-scripts/blob/master/libs.gradle and you're ready to go. Currently I've deployed the `1.0.0.M1` version of `org.springframework.internal:jenkins-commons`

**Comment by marcingrzejszczak** [comment]
Spring Cloud moved out here - https://github.com/spring-cloud/spring-cloud-jenkins-jobs .
