### ISSUE TITLE
Jenkins now uses CF client v2

### ISSUE THREAD

**Issue by snicoll** [spring-io/build-scripts#23]
The Cloudfoundry plugin on Jenkins has been upgrade to use the latest CF client so `org.springframework.jenkins.common.job.CloudFoundryPlugin.pushToCloudFoundry` is probably outdated. 

`SpringStarterProductionBuildMaker` is the only one using it apparently and it uses the default so perhaps this is about upgrading `jenkins-common`?

**Comment by marcingrzejszczak** [comment]
Assuming that the problem was related to setting default value of memory then it got fixed here - https://github.com/spring-io/build-scripts/commit/afec9762407ee76d563ffd2658145c99315c3b0c

**Comment by snicoll** [comment]
Not only. I've created two additional PRs
